acme_resource:
    resource: "@AcmeResourceBundle/Resources/config/routing.yml"
    prefix:   /resource

acme_product:
    resource: "@AcmeProductBundle/Resources/config/routing.yml"
    prefix:   /product

acme_user:
    resource: "@AcmeUserBundle/Resources/config/routing.yml"
    prefix:   /

acme_web:
    resource: "@AcmeWebBundle/Resources/config/routing/main.yml"
    prefix:   /myweb

acme_my_sys:
    resource: "@AcmeMySysBundle/Resources/config/routing.yml"
    prefix:   /sys

acme_iot:
    resource: "@AcmeIOTBundle/Resources/config/routing.yml"
    prefix:   /iot

# These first lines load the all routes defined as @Route() annotations in any
# controller defined inside the src/AppBundle/Controller/ directory. Controllers
# are loaded recursively, so you can separate them into subdirectories.
# If you don't like to add annotations in your applications, you can also define
# the routes in YAML, XML or PHP files.
# See http://symfony.com/doc/current/book/routing.html
app:
    resource: '@AppBundle/Controller/'
    type:     annotation
    prefix:   /blog/{_locale}
    requirements:
        _locale: %app_locales%
    defaults:
        _locale: %locale%

# These lines define a route using YAML configuration. The controller used by
# the route (FrameworkBundle:Template:template) is a convenient shortcut when
# the template can be rendered without executing any logic in your own controller.
# See http://symfony.com/doc/current/cookbook/templating/render_without_controller.html
homepage:
    path: /{_locale}
    requirements:
        _locale: %app_locales%
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    default/homepage.html.twig
        _locale:     %locale%
